name: Docker Image CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
git remote add origin https://github.com/jaylo59/dependabot.yml.git
git branch -M main
git push -u origin mainecho "# dependabot.yml" >> README.md
git init
git add README.md
git commit -m git remote add origin https://github.com/jaylo59/dependabot.yml.git
git branch -M main
git push -u origin mainecho "# dependabot.yml" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/jaylo59/dependabot.yml.git
git push -u origin mainhttps://github.com/jaylo59/dependabot.yml.git
